### ISSUE TITLE
BUG: /v1/voices endpoint broken

### ISSUE THREAD

**Issue by paulrobello** [travisvn/openai-edge-tts#2]
Running via latest docker image under linux.
requests to /v1/voices and /v1/voices/all both fail will internal server error.

```
[2024-10-18 03:25:43,837] ERROR in app: Exception on /v1/voices [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/utils.py", line 21, in decorated_function
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/app/server.py", line 53, in list_voices
    return jsonify({"voices": get_voices()})
                              ^^^^^^^^^^^^
  File "/app/tts_handler.py", line 69, in get_voices
    for v in all_voices if language is None or v['Locale'] == language
             ^^^^^^^^^^
TypeError: 'coroutine' object is not iterable
```

**Comment by travisvn** [comment]
@paulrobello 

Yep — the Docker Hub image has not been updated with the latest code change I made a couple hours ago. 

I wanted to wait and do some more extensive testing before updating at the hub. 

See this response for more information: https://github.com/travisvn/openai-edge-tts/issues/1#issuecomment-2421042922

**Comment by travisvn** [comment]
@paulrobello 

The Docker Hub has been updated with the latest changes and should work as expected 🙂
