### ISSUE TITLE
error messages when using in longer text

### ISSUE THREAD

**Issue by NeverBeLazyG** [travisvn/openai-edge-tts#7]
hi, i get error messages when i use it for longer texts, about 500 words. the sound is played back but my browser pops out this message all the time. any idea ?

i tried it as a docker service and also as a installed python venv . and also on a different server. can you help me ?
![image](https://github.com/user-attachments/assets/0ed13246-5b59-4aaa-99d1-e6282a05e9ae)
![image](https://github.com/user-attachments/assets/ca8c5ec7-4c82-4bfe-aa7c-870ca0bb47e8)

**Comment by travisvn** [comment]
@NeverBeLazyG You'll need to provide the actual error the server is providing for me to be able to help you. 

Refer to the logs in the docker container that arise when this error is shown, or the error message that displays in your terminal when you're running this through Python. 


As an aside, I see your "Response splitting" is set to punctuation. You might want to try the other 2 options there and see if that helps.

**Comment by NeverBeLazyG** [comment]
i tried changing the punctuation settings, didnt help, and this is the docker logs when getting that errors: 
![image](https://github.com/user-attachments/assets/521958fa-a6ba-4ad3-8007-f78ba9de93b8)

any idea ?

**Comment by NeverBeLazyG** [comment]
and i get this messegas also in the container logs:     return self._loop.run_until_complete(task)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete

    return future.result()

           ^^^^^^^^^^^^^^^

  File "/app/tts_handler.py", line 29, in _generate_audio

    await communicator.save(temp_output_file.name)

  File "/usr/local/lib/python3.12/site-packages/edge_tts/communicate.py", line 523, in save

    async for message in self.stream():

  File "/usr/local/lib/python3.12/site-packages/edge_tts/communicate.py", line 506, in stream

    async for message in self.__stream():

  File "/usr/local/lib/python3.12/site-packages/edge_tts/communicate.py", line 482, in __stream

    raise NoAudioReceived(

edge_tts.exceptions.NoAudioReceived: No audio was received. Please verify that your parameters are correct.

172.17.0.1 - - [2024-10-23 21:59:43] "POST /v1/audio/speech HTTP/1.1" 500 401 0.342665

[2024-10-23 21:59:44,698] ERROR in app: Exception on /v1/audio/speech [POST]

Traceback (most recent call last):

  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app

    response = self.full_dispatch_request()

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request

    rv = self.handle_user_exception(e)

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request

    rv = self.dispatch_request()

         ^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request

    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/utils.py", line 27, in decorated_function

    return f(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^

  File "/app/server.py", line 40, in text_to_speech

    output_file_path = generate_speech(text, voice, response_format, speed)

                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/tts_handler.py", line 55, in generate_speech

    return asyncio.run(_generate_audio(text, voice, response_format, speed))

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run

    return runner.run(main)

           ^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run

    return self._loop.run_until_complete(task)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete

    return future.result()

           ^^^^^^^^^^^^^^^

  File "/app/tts_handler.py", line 29, in _generate_audio

    await communicator.save(temp_output_file.name)

  File "/usr/local/lib/python3.12/site-packages/edge_tts/communicate.py", line 523, in save

    async for message in self.stream():

  File "/usr/local/lib/python3.12/site-packages/edge_tts/communicate.py", line 506, in stream

    async for message in self.__stream():

  File "/usr/local/lib/python3.12/site-packages/edge_tts/communicate.py", line 482, in __stream

    raise NoAudioReceived(

edge_tts.exceptions.NoAudioReceived: No audio was received. Please verify that your parameters are correct.

172.17.0.1 - - [2024-10-23 21:59:44] "POST /v1/audio/speech HTTP/1.1" 500 401 1.175931

[2024-10-23 21:59:45,081] ERROR in app: Exception on /v1/audio/speech [POST]

Traceback (most recent call last):

  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app

    response = self.full_dispatch_request()

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request

    rv = self.handle_user_exception(e)

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request

    rv = self.dispatch_request()

         ^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request

    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/utils.py", line 27, in decorated_function

    return f(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^

  File "/app/server.py", line 40, in text_to_speech

    output_file_path = generate_speech(text, voice, response_format, speed)

                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/tts_handler.py", line 55, in generate_speech

    return asyncio.run(_generate_audio(text, voice, response_format, speed))

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run

    return runner.run(main)

           ^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run

    return self._loop.run_until_complete(task)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete

    return future.result()

           ^^^^^^^^^^^^^^^

  File "/app/tts_handler.py", line 29, in _generate_audio

    await communicator.save(temp_output_file.name)

  File "/usr/local/lib/python3.12/site-packages/edge_tts/communicate.py", line 523, in save

    async for message in self.stream():

  File "/usr/local/lib/python3.12/site-packages/edge_tts/communicate.py", line 506, in stream

    async for message in self.__stream():

  File "/usr/local/lib/python3.12/site-packages/edge_tts/communicate.py", line 482, in __stream

    raise NoAudioReceived(

edge_tts.exceptions.NoAudioReceived: No audio was received. Please verify that your parameters are correct.

172.17.0.1 - - [2024-10-23 21:59:45] "POST /v1/audio/speech HTTP/1.1" 500 401 0.348832

172.17.0.1 - - [2024-10-23 21:59:45] "POST /v1/audio/speech HTTP/1.1" 200 57299 0.716773

**Comment by travisvn** [comment]
I'm not sure. Are you running in Docker? If not, you might want to try that and running directly from the Docker Hub container. 

And make sure the size of your payload to the server (amount of text) is within a reasonable amount. On top of that, ensure you're not making too many requests too quickly, as there are some nebulous rate limits.

**Comment by NeverBeLazyG** [comment]
i tried it both. i tried with installing it directly on my machine, and also in docker. same result. i think it has something todo with the rate limit. its strange. dont you get this error ever ? i dont make any special request. i am just asking the chat llm somthing like this: " write me a sci fi story", then i click the speaker button in openwebui. and in 80% of the time i get this error. the voice is still there. i hear the voice talking the text, but, with all that error messages popping up. and what i also noticed. when i get this error, i cant stop the voice until it read the full text. normally its possible to stop it when clicking the speaker symbol again. is it possible you put in a milisecond option or somthing, where you can add somthing like 1-5sec delay between new requests that edge tts can do to ms servers. maybe that can help. its just an idea

**Comment by NeverBeLazyG** [comment]
my idea would be like this: you start the docker container with an extra parameter letz say docker run .... -- 500 . the 500 stands for  ms. and yo put that 500ms delay in front of the edge-tts request, every time it starts edge-tts it delays it for 500 ms.
